#if !defined __NNNMINIGAMELIB_MINIGAMELAYOUTPARAMNAME_H__
#define __NNNMINIGAMELIB_MINIGAMELAYOUTPARAMNAME_H__

//
//
//



#define MINIGAME_LAYOUTPARAM_NEXTX (0)
#define MINIGAME_LAYOUTPARAM_NEXTY (1)
#define MINIGAME_LAYOUTPARAM_STARTX (2)
#define MINIGAME_LAYOUTPARAM_STARTY (3)


#endif
/*_*/

