//
// commonMode.h
//

#if !defined __NNNLIB_COMMONMODE__
#define __NNNLIB_COMMONMODE__

// system use 1-49

//0 Žg—p•s‰Â
#define NOTHING_MODE 1
#define LOGO_MODE 2
#define OPENING_MODE 3
#define TITLE_MODE 4
#define LOAD_MODE 5
#define SAVE_MODE 6
#define BACKLOG_MODE 7
#define LISTENBGM_MODE 8
#define SELECTMESSAGE_MODE 9
#define PRINTMESSAGE_MODE 10
#define DRAW_MODE 11
#define CONFIG_MODE 12
#define SYSTEMMENU_MODE 13
#define PRINTOVERRAP_MODE 14
#define OMAKE_MODE 15
#define SELECTCGCHARA_MODE 16
#define SELECTCG_MODE 17
#define SELECTSCENE_MODE 18
//19
#define SELECTSCENECHARA_MODE 20
#define CDERROR_MODE 21
#define SELECTPLACE_MODE 22
#define PRINTCG_MODE 23
#define SELECTZUKAN_MODE 24
#define SELECTMOVIECHARA_MODE 25
#define SELECTMOVIE_MODE 26
#define PRINTMOVIE_MODE 27
//28
#define NAMEINPUT_MODE 29
#define PRINTCALENDAR_MODE 30
#define SELECTHEROIN_MODE 31
#define CODECERROR_MODE 32
#define MYPRINTRESULT_MODE 33
#define SELECTCHART_MODE 34
#define SELECTPLACE2_MODE 35
//36
//37
//38
//39
#define MINIGAME_MODE 40
#define SELECTOBJECT_MODE 41
#define PRINTACHIEVEMENT_MODE 42
#define PRINTTERM_MODE 43
#define LISTENVOICE_MODE 44
#define CARDSYSTEM_MODE 45
#define KANJIINPUT_MODE 46
#define PRINTITEM_MODE 47
//48
//49





#endif
/*_*/

