//
// 
//

#if !defined __NNNLIB_SYSTEMPARAMLIST__
#define __NNNLIB_SYSTEMPARAMLIST__


#define NNNPARAM_BGMMODE (0)
//
#define NNNPARAM_SKIPMODE (2)
//
#define NNNPARAM_SCREENMODE (4)
//
#define NNNPARAM_AUTOMODE (6)
//
#define NNNPARAM_USERDEFINEMODE (50)

#define NNNPARAM_MUSICVOLUME (100)
#define NNNPARAM_SOUNDVOLUME (101)
#define NNNPARAM_VOICEVOLUME (102)
#define NNNPARAM_MOVIEVOLUME (103)
#define NNNPARAM_SOUNDVOICEVOLUME (104)
#define NNNPARAM_MESSAGESPEED (105)
#define NNNPARAM_WINDOWPERCENT (106)
#define NNNPARAM_AUTOSPEEDSLIDER (107)

//
#define NNNPARAM_USERDEFINEVOLUME (150)

#define NNNPARAM_MUSICSWITCH (200)
#define NNNPARAM_SOUNDSWITCH (201)
#define NNNPARAM_VOICESWITCH (202)
#define NNNPARAM_MOVIESWITCH (203)
#define NNNPARAM_SOUNDVOICESWITCH (204)

//
#define NNNPARAM_USERDEFINESWITCH (250)

#define NNNPARAM_EXPMODE (300)
#define NNNPARAM_EXPCHECK (400)

#define NNNPARAM_CHARAVOICEVOLUME (500)


#define NNNBGMMODE_MIDI (1)
#define NNNBGMMODE_CDDA (2)
#define NNNBGMMODE_WAVE (3)


#define NNNSKIPMODE_NORMAL (0)
#define NNNSKIPMODE_ALL (1)


#define NNNSCREENMODE_NORMAL (0)
#define NNNSCREENMODE_FULL (1)

#define NNNAUTOMODE_OFF (0)
#define NNNAUTOMODE_ON (1)








//// not used!
//#define SYSTEMPARAM_MIDIMODE (0)
//#define SYSTEMPARAM_VOICEMODE (1)
//#define SYSTEMPARAM_SKIPMODE (2)
//#define SYSTEMPARAM_MESSAGESPEED (3)
//#define SYSTEMPARAM_SCREENMODE (4)
//#define SYSTEMPARAM_BGMMODE (5)
//#define SYSTEMPARAM_AUTOMODE (6)

//#define SYSTEMPARAM_MUSICVOLUME (100)
//#define SYSTEMPARAM_SOUNDVOLUME (101)
//#define SYSTEMPARAM_VOICEVOLUME (102)





#endif
/*_*/

