//
// commonSystemSoundName.h
//

#if !defined __NNNLIB_COMMONSYSTEMSOUNDNAME__
#define __NNNLIB_COMMONSYSTEMSOUNDNAME__


#define COMMON_SYSTEMSOUND_OK (0)
#define COMMON_SYSTEMSOUND_CANCEL (1)
#define COMMON_SYSTEMSOUND_PON (2)
#define COMMON_SYSTEMSOUND_OK2 (3)
#define COMMON_SYSTEMSOUND_PAGE (4)


#endif
/*_*/

