//
// effectlist.h
//

#if !defined __NYANEFFECTLIB_EFFECTLIST__
#define __NYANEFFECTLIB_EFFECTLIST__


#define EFFECT_NOP 0
//#define EFFECT_WAITMODE 1
#define EFFECT_MAE 1
	//前の続きのエフェクト番号として予約	エフェクトそのものは存在しにゃい


#define EFFECT_PUT 2
#define EFFECT_LOCATE 3
#define EFFECT_VIEW 4
#define EFFECT_LMOVE 5
#define EFFECT_VMOVE 6
#define EFFECT_PMOVE 7
#define EFFECT_TRANS 8
#define EFFECT_CTRANS 9
#define EFFECT_FADEIN 10
#define EFFECT_FADEOUT 11
#define EFFECT_FLOWER 12
#define EFFECT_RAIN 13
#define EFFECT_SNOW 14
#define EFFECT_SAN 15
#define EFFECT_OVERRAP 16
#define EFFECT_FLASH 17
#define EFFECT_SHAKE 18
#define EFFECT_ANIME 19
#define EFFECT_LIGHT 20
#define EFFECT_HANABI 21
#define EFFECT_KAGEROU 22
#define EFFECT_RASTER 23
#define EFFECT_WATER 24
#define EFFECT_WARP 25
#define EFFECT_REMEMBER 26
#define EFFECT_KE 27
#define EFFECT_CIRCLE 28
#define EFFECT_SUNA 29
#define EFFECT_SOFTFOCUS 30
#define EFFECT_NEGA 31
#define EFFECT_MELTDOWN 32
#define EFFECT_RELEAF 33
#define EFFECT_BGBACK 34
#define EFFECT_BGKAKUSAN 35
#define EFFECT_STRETCH 36
#define EFFECT_BGZOOMIN 37
#define EFFECT_FACE 38
#define EFFECT_SCROLL 39
#define EFFECT_CHANGE 40
#define EFFECT_CALENDAR 41
#define EFFECT_KIRA 42
#define EFFECT_MOZAIC 43
#define EFFECT_MOUSEMOZAIC 44
#define EFFECT_SURA 45
#define EFFECT_NAGASHI 46
#define EFFECT_NIJIMASU 47
#define EFFECT_BOSSDEATH 48
#define EFFECT_BGDARK 49
#define EFFECT_GRADATION 50
#define EFFECT_TAIYO 51

#define EFFECT_MOVE 52
#define EFFECT_TARE 53
#define EFFECT_FILL 54
#define EFFECT_OLDFILM 55
#define EFFECT_RAIN2 56
#define EFFECT_SNOW2 57

#define EFFECT_MIRRORCHARA 58

#define EFFECT_SIMPLEWIPE 59
#define EFFECT_MASKWIPE 60

#define EFFECT_SPECIALMOVE 61
#define EFFECT_BEZIERMOVE 62

#define EFFECT_KOMAANIME 63
#define EFFECT_TURN 64

#define EFFECT_STRETCHBLT 65

#define EFFECT_BUFFER 66

#define EFFECT_PERS 67
#define EFFECT_CURTAIN 68

#define EFFECT_HAMON 69
#define EFFECT_HANABIRA 70
#define EFFECT_HOTARU 71

#define EFFECT_MEISAI 72

#define EFFECT_GET 73
#define EFFECT_BURA 74

#define EFFECT_ONCE 75

#define EFFECT_SLASH 76

#define EFFECT_BOKASHI 77

#define EFFECT_KOMOREBI 78

#define EFFECT_FULLANIME 79

#define EFFECT_STAFFROLL 80

#define EFFECT_HAHEN 81

#define EFFECT_CLOUD 82

#define EFFECT_BEACH 83

#define EFFECT_FUSUMA 84



#define EFFECT_SPEEDLINE 85

#define EFFECT_ZANTETSU 86

#define EFFECT_GEOCIRCLE 87
#define EFFECT_GEOPOLYGON 88
#define EFFECT_GEOTORUS 89

#define EFFECT_CHARAFLASH 90


#define EFFECT_WATERFALL 91

#define EFFECT_SOYOSOYO 92

#define EFFECT_GRASSPLANE 93

#define EFFECT_POLESCROLL 94
#define EFFECT_WATERDROP 95

#define EFFECT_RAINBOW 96

#define EFFECT_BATHWINDOW 97

#define EFFECT_MEPACHIKUCHIPAKU 98

#define EFFECT_COLORADDSUB 99

#define EFFECT_HAIKEIYURE 100

#define EFFECT_MOVEMASKWIPE 101

#define EFFECT_RAIN4 102

#define EFFECT_TARGET1 103
#define EFFECT_KONOHA 104

#define EFFECT_MOVIE_WARP 105

#define EFFECT_NOISE 106
#define EFFECT_CHARARASTER 107

#define EFFECT_HAE 108
#define EFFECT_OLDLAMP 109

#define EFFECT_CHARAGHOST 110
#define EFFECT_FISH 111

#define EFFECT_CHARAMETAL 112

#define EFFECT_LUPIN 113

#define EFFECT_GEOBOX 114
#define EFFECT_GEOCIRCLEADD 115
#define EFFECT_GEOTORUSADD 116
#define EFFECT_GEOPOLYGONADD 117
#define EFFECT_GEOBOXADD 118

#define EFFECT_BSPLINE2 119

#define EFFECT_COLORBALANCE 120

#define EFFECT_DUALMASK 121
#define EFFECT_CLIPZOOMIN 122

#define EFFECT_CHARAMASKAPPEAR 123

#define EFFECT_CHARAGREY 124
#define EFFECT_CHARABOKASHI 125
#define EFFECT_BGBOKASHI 126
#define EFFECT_SEPIA 127
#define EFFECT_LAYERSEPIA 128
#define EFFECT_LAYERGREY 129
#define EFFECT_SAIKE 130
#define EFFECT_ADDSUB 131
#define EFFECT_CHARABURE 132
#define EFFECT_SENTENCE 133

#define EFFECT_KILLEFFECT 134
	//エフェクトクリアーとして予約	エフェクトそのものは存在しにゃい


#define EFFECT_LAYERHAMON 135
#define EFFECT_TACLIP 136

#define EFFECT_ANIMATION 137



#endif
/*_*/

